### ISSUE TITLE
Illustrate Recreating Preferred Workflow

### ISSUE THREAD

**Issue by LinkedFate** [LinkedFate/CS471WorkflowsHomeworkAssignment#12]
References user story #1

Recreate the preferred workflow described in the last task.

## TODO:
- [x] Create a new PR having the **base** branch `master` and the **compare** branch `extra_credit`
- [x] Edit the description of the PR to reference this task
- [x] Understand the commits and changes made to the PR
    - :thumbsup: notice that the commits in the branch **DO NOT** reference this task `#12`. This is intentional, as to not clutter this task with references of commits containing partial implementations (i.e., that do not contain the entire change in one commit), and which can be altered in subsequent commits in the same branch
- [x] In the PR, use the `Squash and merge` option to integrate the changes into `master` and the commit message should be `Closes #12 (#<ID_PR>)`, and remove the extended description in the commit
- [x] Use the GitHub interface to delete the branch of the PR after successfully integrating it into `master`
